version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB=mongodb
    networks:
      - proxy
      - internal
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ${PWD}/data/db:/data/db
    networks:
      - internal
      - proxy
    ports:
      - '27017:27017'
